import tkinter as tk
from typing import TypeVar, Type
T = TypeVar('T')


class Frame(tk.Frame):
    width: int
    height: int
    origin: int
    globsize: list[int]
    canvas: tk.Canvas
    def __init__(self, parent: tk.Tk): ...
    def create_token(self, x: int, y: int, color: str, **kwargs) -> tk._CanvasItemId: ...
    def create_curve(self, inputs: list[list[int]], func: function, update_func: function | None = None, cls: Type[T] | None = None, **kwargs) -> tuple[None | T, tk._CanvasItemId, list[tk._CanvasItemId]]: ...
    def create_rectangle(self, inputs: list[list[int]], func: function, update_func: function | None = None, cls: Type[T] | None = None, **kwargs) -> tuple[None | T, tk._CanvasItemId, list[tk._CanvasItemId]]: ...
    def create_oval(self, inputs: list[list[int]], func: function, update_func: function | None = None, cls: Type[T] | None = None, **kwargs) -> tuple[None | T, tk._CanvasItemId, list[tk._CanvasItemId]]: ...
